### PR TITLE
Patch for Jenkins Worker Fix

### PR DESCRIPTION
**Pull request by shadinaif**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by shadinaif** [comment]
@OmarEdraak this related to the previous PR https://github.com/Edraak/edx-configuration/pull/6

I made a copy-paste mistake !

**Comment by OmarEdraak** [comment]
Thanks @shadinaif! Looks great!

**Comment by shadinaif** [comment]
@OmarEdraak I have reverted the the `make upgrade` effect as requested in https://github.com/Edraak/edx-configuration/pull/6 .
Please take a look again
`git checkout 2c2f066225160175f2c43f06d7de3b30abafe8e3 <<file path>>`

**Comment by shadinaif** [comment]
Thank you @OmarEdraak !

**Pull request merged**
